language: python
sudo: required
python:
  - "3.6"
install:
  - pip install -U codeclimate-test-reporter pipenv
  - pipenv install --dev
  - pip install -I "coverage>4.0,<4.4"
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - export WKHTMLTOPDF_LIBRARY_PATH="$PWD/wkhtmltox/lib/libwkhtmltox"
script:
  - py.test
after_success:
  - CODECLIMATE_REPO_TOKEN=c13adb6ff4fe2169217bd8e2a646b7d776ac77cf3c63f71fb4b7466fbc4f9b0d codeclimate-test-reporter
